# Generated by Django 5.1.5 on 2025-03-20 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_classlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='admin_app.classlevel'),
            preserve_default=False,
        ),
    ]
