# Generated by Django 5.1.5 on 2025-03-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_subject_class_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlevel',
            name='name',
        ),
        migrations.AddField(
            model_name='classlevel',
            name='level',
            field=models.CharField(choices=[('PlusOne', 'Plus One'), ('PlusTwo', 'Plus Two')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
