# Generated by Django 5.1.5 on 2025-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_remove_classlevel_name_classlevel_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='classlevel',
            name='syllabus',
            field=models.CharField(choices=[('Kerala', 'Kerala Syllabus'), ('CBSE', 'CBSE Syllabus')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='level',
            field=models.CharField(choices=[('PlusOne', 'Plus One'), ('PlusTwo', 'Plus Two')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('level', 'syllabus')},
        ),
    ]
